apiVersion: v1
kind: Service
metadata:
  name: my-cluster-service
spec:
  selector: # label to choose pods which will route traffic to it 
    name: web-app
  ports: 
  - protocol: TCP
    port: 80
    targetPort: 80
