# create rolebinding to bind role to subject (service account)
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: rbac-lab
  name: view-pods-binding
subjects:
  - kind: ServiceAccount
    name: dev-user
    namespace: rbac-lab
roleRef:
  kind: Role
  name: view-pods
  apiGroup: rbac.authorization.k8s.io


# to check if service account user hase roles 
# kubectl auth can-i list pods --namespace rbac-lab --as=system:serviceaccount:rbac-lab:dev- 